spring:
  application:
    name: DeveloperCommunity
  config:
    import: "optional:file:.env.properties"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/github"

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    hibernate:
#      ddl-auto: create
      ddl-auto: update
#      ddl-auto: none
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.client.RestTemplate: DEBUG
    org.springframework.web.reactive.function.client: DEBUG
server:
  port: 30000